// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stratom.Form.DataAccessLayer;

namespace Stratom.Form.DataAccessLayer.Migrations
{
    [DbContext(typeof(StratomDbContext))]
    [Migration("20201101163411_1stMigraton")]
    partial class _1stMigraton
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Activite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Souscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("Activite");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.AssuranceDommage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("AssuranceDommage");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.AssurancePersonne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("AssurancePersonne");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.ContratsPortefeuille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autre")
                        .HasColumnType("text");

                    b.Property<string>("CotisationAnnuelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateSouscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Garantie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("ContratsPortefeuille");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.DescriptionActivite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactFaceAface")
                        .HasColumnType("text");

                    b.Property<string>("ContactFonction")
                        .HasColumnType("text");

                    b.Property<string>("ContactOrigine")
                        .HasColumnType("text");

                    b.Property<string>("ContactRole")
                        .HasColumnType("text");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("text");

                    b.Property<string>("EntretienDeroulement")
                        .HasColumnType("text");

                    b.Property<string>("EntretienObjectifs")
                        .HasColumnType("text");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFiche")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("DescriptionActivite");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("Etudiant");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Fiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActiviteType")
                        .HasColumnType("bit");

                    b.Property<bool>("Concerne")
                        .HasColumnType("bit");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fiche");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.FicheClientProspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgesEnfants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Anciennete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autre")
                        .HasColumnType("text");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContratsPortefeuilleId")
                        .HasColumnType("int");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClient")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NbEnfants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroFiche")
                        .HasColumnType("int");

                    b.Property<string>("Placements")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Revenus")
                        .HasColumnType("int");

                    b.Property<string>("Sexe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationFamiliale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationProfessionnelle")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TauxImposition")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("FicheClientProspect");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.FicheContexteSimplifiee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionsCommerciales")
                        .HasColumnType("text");

                    b.Property<string>("ActivitesEntreprise")
                        .HasColumnType("text");

                    b.Property<string>("Cible")
                        .HasColumnType("text");

                    b.Property<string>("CompagnieMandante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntrepriseNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Historique")
                        .HasColumnType("text");

                    b.Property<int>("NumeroFiche")
                        .HasColumnType("int");

                    b.Property<string>("PresentationPortefeuilleClients")
                        .HasColumnType("text");

                    b.Property<string>("ReductionsAutre")
                        .HasColumnType("text");

                    b.Property<string>("ReductionsMontant")
                        .HasColumnType("text");

                    b.Property<string>("ReductionsNature")
                        .HasColumnType("text");

                    b.Property<string>("ReductionsPeriode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("FicheContexteSimplifiee");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.FicheFin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AutoEvaluation")
                        .HasColumnType("text");

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("InformationsAConserver")
                        .HasColumnType("text");

                    b.Property<int>("NumeroFiche")
                        .HasColumnType("int");

                    b.Property<string>("PlanificationActions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("FicheFin");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Phases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFiche")
                        .HasColumnType("int");

                    b.Property<string>("PhaseAsseoirVente")
                        .HasColumnType("text");

                    b.Property<string>("PhaseConclusion")
                        .HasColumnType("text");

                    b.Property<string>("PhaseContact")
                        .HasColumnType("text");

                    b.Property<string>("PhaseDecouverte")
                        .HasColumnType("text");

                    b.Property<string>("PhasePriseConge")
                        .HasColumnType("text");

                    b.Property<string>("PhaseTransition")
                        .HasColumnType("text");

                    b.Property<string>("PhaseVente")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Activite", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("Activite")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.AssuranceDommage", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("AssurancesDommage")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.AssurancePersonne", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", null)
                        .WithMany("AssurancesPersonne")
                        .HasForeignKey("FicheId");
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.ContratsPortefeuille", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("ContratsPortefeuille")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.DescriptionActivite", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("DescriptionActivite")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Etudiant", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("Etudiant")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.FicheClientProspect", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("FicheClientProspect")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.FicheContexteSimplifiee", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("FicheContexteSimplifiee")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.FicheFin", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("FicheFin")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratom.Form.DataAccessLayer.Models.Phases", b =>
                {
                    b.HasOne("Stratom.Form.DataAccessLayer.Models.Fiche", "Fiche")
                        .WithMany("Phase")
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
